version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.78.0
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
            cargo --version
      - run:
          name: Build
          command: |
            cargo build
      - run:
          name: Clippy
          command: |
            cargo clippy
      - run:
          name: Tests
          command: |
            cargo test